language: node
rvm:
  - 2.2.4
before_script:
  - mkdir testdb
  - mongod --port 27017 --dbpath testdb --replSet rs0 --oplogSize 20 --noprealloc --fork --smallfiles --logpath mongodb.log
  - sleep 3
  - mongo admin --eval 'printjson(rs.initiate());'
  - sleep 20
script:
  - bundle exec rspec
